version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sonpike

  tor:
    build:
      context: .docker/tor
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      - sonpike

networks:
  sonpike:
    external: false
    name: sonpike